// <auto-generated />
using McShare.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McShare.Migrations
{
    [DbContext(typeof(CustomerContext))]
    partial class CustomerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("McShare.Model.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Customer ID");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<double>("Balance")
                        .HasColumnType("float")
                        .HasColumnName("Balance");

                    b.Property<double>("ContactDetail")
                        .HasColumnType("float")
                        .HasColumnName("Contact Detail");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Customer Name");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Customer Type");

                    b.Property<string>("DOB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Date of Birth");

                    b.Property<string>("IncorpDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Incorp Date");

                    b.Property<int>("NumShares")
                        .HasColumnType("int")
                        .HasColumnName("Number of Shares");

                    b.Property<string>("RegistrationNum")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Registration Number");

                    b.Property<double>("SharesPrice")
                        .HasColumnType("float")
                        .HasColumnName("Shares per unit price");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("McShare.Model.ErrorLog", b =>
                {
                    b.Property<int>("ErrorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Error ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ErrorDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Error Descrition");

                    b.HasKey("ErrorID");

                    b.ToTable("ErrorLog");
                });
#pragma warning restore 612, 618
        }
    }
}
